$gv      = dotnet gitversion /output json | ConvertFrom-Json
$semVer  = $gv.SemVer                                                          # e.g. 0.0.1-alpha.1
$version = "$($gv.VersionSourceSemVer).$($gv.CommitsSinceVersionSource)"
"{VersionSourceSemVer}.{CommitsSinceVersionSource}"
$cs = @"
// auto-generated by version.ps1 — do not edit
namespace Skyplan {
    internal static class VersionInfo {
        public const string Version = "$version";
    }
}
"@
Set-Content -Path "$PSScriptRoot\Skyplan\VersionInfo.cs" -Value $cs -Encoding UTF8

$layersPath = "$PSScriptRoot\SkyPlanUI\src\layers_default.json"
$layers = Get-Content $layersPath -Raw | ConvertFrom-Json
$layers.version = $version
$layers | ConvertTo-Json -Depth 10 | Set-Content $layersPath -Encoding UTF8

# $csprojPath = "$PSScriptRoot\skyplan\skyplan.csproj"
# $xml = [xml](Get-Content $csprojPath -Raw)
# $xml.Project.PropertyGroup[0].Version = $semVer
# $xml.Project.PropertyGroup[0].InformationalVersion = $version
# $xml.Save($csprojPath)

Write-Output $version
